---
- name: Full install bio
  hosts: BIO
  become: yes

  roles:
    - rename_and_add_hostname_localhost
    - install_python
    - install_docker
    - add_user_docker
    - install_ca
    - copy_bio_compose
    - set_hostname_docker-compose
    - resolve_local
    - install_gnupg2