---
- name: Playbook copy and start index.html
  hosts: all
  become: yes

  vars:
    source_file: /home/avk/MyWebSite/index.html
    destin_file: /var/www/html

  tasks:
  - name: Install Apache Server
    apt: name=apache2 state=latest

  - name: copy index.html
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start Web Server
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
