---
- name: Install default Apache Web Server
  hosts: all
  become: yes

  tasks:
  - name: Chek and print OS version
    debug: var=ansible_os_family

  - block:    # ===============Block for REDHAT=========

    - name: Install Apache WebServer for REDHAT
      yum: name=httpd state=latest

    - name: Start Apache and Enable
      service: name=httpd state=stated enabled=yes

    when: ansible_os_family == "RedHat"

  - block:    # =============Block for UBUNTU======== 

    - name: Install Apache WebServer
      apt: name=apache2 state=latest

    - name: Start Apache and Enable
      service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"