---
- name: Playbook copy and start index.html
  hosts: all
  become: yes

  vars:
    source_folder: /home/avk/MyWebSite/
    destin_folder: /var/www/html

  tasks:
  - name: Install Apache Server
    apt: name=apache2 state=latest

  - name: Generate INDEX.HTML file 
    template: src={{ source_folder }}/index.j2 dest={{ destin_folder }}/index.html mode=0555
    notify: Restart Apache

  - name: Copy file to Web Server
    copy: src={{ source_folder }}/{{ item }} dest={{ destin_folder }} mode=0555
    loop:
      - "privet.txt"
    notify: Restart Apache

  - name: Start Web Server
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted