---
# tasks file for install_docker
- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: yes

- name: Add Docker PGP key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repo Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present

- name: Start Install Docker and update repositories
  apt:
    name: 
      - docker-ce
      - docker-compose
    update_cache: yes