---
# tasks file for install_gnupg2
- name: Set hostname in docker-compose
  replace:
    path: /home/bio/docker-compose/bio_chromium/docker-compose.yml
    regexp: '^    - HOSTNAME='
    replace: '    - HOSTNAME={{ HOSTNAME_BIO }}'